spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    username: root
    url: jdbc:mysql://localhost/users?createDatabaseIfNotExist=true&useSSL=false
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest