version: '3'

services: 
  database:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
    - database_volume:/var/lib/mysql

  rabbit:
    image: rabbitmq:management-alpine
    ports:
    - "5672:5672"
    - "15672:15672"

  user:
    image: microservice-user
    ports:
    - "8080:8080"
    environment: 
    - DB_HOST=database
    - RABBIT_HOST=rabbit

volumes:
  database_volume:
